# -*- coding: utf-8 -*-
"""model_trainig.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P_pc1X1usI6pMP0qrZrShKkP9cu--JaG
"""

!pip install -q pandas pyarrow fastparquet torch torchvision transformers fastapi uvicorn python-multipart python-jose[cryptography] Pillow requests

from google.colab import drive
drive.mount('/content/drive')

import zipfile
import os
import pandas as pd

zip_path = '/content/drive/MyDrive/Файлы для итоговой/subcategory_images.zip'

if os.path.exists(zip_path):
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall('data/images')
    print(f"Фото распакованы в data/images/")
else:
    print(f"Файл не найден: {zip_path}")

    parent_dir = '/content/drive/MyDrive/Файлы для итоговой/'
    if os.path.exists(parent_dir):
        print(f"Содержимое папки: {os.listdir(parent_dir)}")

posts = pd.read_parquet('/content/drive/MyDrive/Файлы для итоговой/posts.parquet')
photos = pd.read_parquet('/content/drive/MyDrive/Файлы для итоговой/photos.parquet')

print("Posts columns:", posts.columns.tolist())
print("Photos columns:", photos.columns.tolist())
print(f"\nPosts: {len(posts)} записей")
print(f"Photos: {len(photos)} записей")

print("\nПример поста:")
print(posts.iloc[0].to_dict())

print("\nПример фото:")
print(photos.iloc[0].to_dict())

if 'category' in posts.columns:
    print(f"\nУникальные категории: {posts['category'].nunique()}")
    print(posts['category'].value_counts().head(10))

import os
import pandas as pd

os.makedirs('data', exist_ok=True)
os.makedirs('models', exist_ok=True)
print("Папки data/ и models/ созданы")

photos_clean = photos.rename(columns={
    'PostId': 'post_id',
    'Url': 'photo_url'
})

posts_clean = posts.rename(columns={
    'Id': 'post_id',
    'Text': 'text',
    'categoryname': 'category'
})

photos_grouped = photos_clean.groupby('post_id')['photo_url'].apply(list).reset_index()
photos_grouped.columns = ['post_id', 'photo_urls']

print(f"Сгруппировано фото: {len(photos_grouped)} постов с фотографиями")

df_merged = posts_clean.merge(photos_grouped, on='post_id', how='left')

df_merged['photo_urls'] = df_merged['photo_urls'].apply(lambda x: x if isinstance(x, list) else [])

print(f"Итого записей: {len(df_merged)}")
print(f"Постов с фото: {df_merged['photo_urls'].apply(len).gt(0).sum()}")
print(f"Постов без фото: {(df_merged['photo_urls'].apply(len) == 0).sum()}")

if (df_merged['photo_urls'].apply(len) > 0).any():
    sample = df_merged[df_merged['photo_urls'].apply(len) > 0].iloc[0]
    print(f"\nПример поста с фото:")
    print(f"ID: {sample['post_id']}")
    print(f"Категория: {sample['category']}")
    print(f"Текст: {sample['text'][:100]}")
    print(f"Фото: {len(sample['photo_urls'])} шт.")

df_merged.to_parquet('data/merged_data.parquet', index=False)
print("\nСохранено в data/merged_data.parquet")

posts_clean.to_parquet('data/posts_clean.parquet', index=False)
photos_clean.to_parquet('data/photos_clean.parquet', index=False)
print("Также сохранено: posts_clean.parquet, photos_clean.parquet")

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score
import joblib
import os

df = pd.read_parquet('data/merged_data.parquet')
print(f"Загружено записей: {len(df)}")

print(f"\nУникальные категории в данных:")
print(df['category'].value_counts())

df_train = df[df['category'].notna() & df['text'].notna()].copy()
df_train['text'] = df_train['text'].astype(str).str.strip()
df_train['category'] = df_train['category'].astype(str).str.strip()

print(f"\nПосле фильтрации: {len(df_train)} записей")
print(f"Уникальных категорий: {df_train['category'].nunique()}")

le_category = LabelEncoder()
df_train['category_encoded'] = le_category.fit_transform(df_train['category'])

print(f"\nМаппинг категорий → код:")
for i, cat in enumerate(le_category.classes_):
    print(f"  {i}: '{cat}'")

if len(le_category.classes_) > 0:
    sample_cat = le_category.classes_[0]
    encoded = le_category.transform([sample_cat])[0]
    decoded = le_category.inverse_transform([encoded])[0]
    print(f"\nТест: '{sample_cat}' → {encoded} → '{decoded}'")

train_texts, test_texts, train_labels, test_labels = train_test_split(
    df_train['text'],
    df_train['category_encoded'],
    test_size=0.2,
    random_state=42,
    stratify=df_train['category']
)

print(f"\nTrain: {len(train_texts)}, Test: {len(test_texts)}")

vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    min_df=3,
    max_df=0.8,
    lowercase=True
)

X_train = vectorizer.fit_transform(train_texts)
X_test = vectorizer.transform(test_texts)

print(f"Векторизовано: {X_train.shape[1]} признаков")

print("\nОбучение модели")
model_category = LogisticRegression(
    max_iter=1000,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)
model_category.fit(X_train, train_labels)

y_pred = model_category.predict(X_test)
print(f"\nAccuracy на тесте: {accuracy_score(test_labels, y_pred):.4f}")
print("\nClassification Report:")
print(classification_report(test_labels, y_pred, target_names=le_category.classes_, zero_division=0))

os.makedirs('models', exist_ok=True)
joblib.dump(model_category, 'models/category_model.pkl')
joblib.dump(vectorizer, 'models/category_vectorizer.pkl')
joblib.dump(le_category, 'models/category_encoder.pkl')
print("\nМодели сохранены в models/")

import os
from PIL import Image
from torchvision import transforms
from torch.utils.data import Dataset, DataLoader

IMG_DIR = '/content/data/images/dataset'

subcategories = [d for d in os.listdir(IMG_DIR) if os.path.isdir(os.path.join(IMG_DIR, d))]
print(f"Найдено подкатегорий: {len(subcategories)}")
print(f"Примеры: {subcategories[:10]}")

subcategory_to_idx = {name: idx for idx, name in enumerate(subcategories)}
idx_to_subcategory = {idx: name for name, idx in subcategory_to_idx.items()}

class SubcategoryDataset(Dataset):
    def __init__(self, root_dir, class_to_idx, transform=None):
        self.samples = []
        self.transform = transform

        for class_name, idx in class_to_idx.items():
            class_path = os.path.join(root_dir, class_name)
            if not os.path.isdir(class_path):
                continue
            for fname in os.listdir(class_path):
                if fname.lower().endswith(('.jpg', '.jpeg', '.png')):
                    self.samples.append((os.path.join(class_path, fname), idx))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        return image, label, img_path

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

dataset = SubcategoryDataset(IMG_DIR, subcategory_to_idx, transform=transform)
print(f"Всего изображений: {len(dataset)}")

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models
from torch.utils.data import random_split

train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False, num_workers=2)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Используем: {device}")

model_subcategory = models.resnet50(pretrained=True)
num_ftrs = model_subcategory.fc.in_features
model_subcategory.fc = nn.Linear(num_ftrs, len(subcategories))
model_subcategory = model_subcategory.to(device)

for name, param in model_subcategory.named_parameters():
    if 'fc' not in name and 'layer4' not in name:
        param.requires_grad = False

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(filter(lambda p: p.requires_grad, model_subcategory.parameters()), lr=1e-3)

def train_epoch(model, loader, epoch):
    model.train()
    running_loss, correct = 0, 0
    for images, labels, _ in loader:
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
        _, preds = torch.max(outputs, 1)
        correct += (preds == labels).sum().item()
    acc = correct / len(loader.dataset)
    print(f"Epoch {epoch+1}: Loss={running_loss/len(loader):.4f}, Acc={acc:.4f}")

for epoch in range(5):
    train_epoch(model_subcategory, train_loader, epoch)

torch.save(model_subcategory.state_dict(), 'models/subcategory_model.pth')

import json
with open('models/subcategory_mapping.json', 'w', encoding='utf-8') as f:
    json.dump({'idx_to_subcategory': idx_to_subcategory, 'subcategories': subcategories}, f, ensure_ascii=False, indent=2)
print("Модель и маппинги сохранены!")

from google.colab import files
import os

models_to_download = [
    'models/category_model.pkl',
    'models/category_vectorizer.pkl',
    'models/category_encoder.pkl',
    'models/subcategory_model.pth',
    'models/subcategory_mapping.json'
]

for model_path in models_to_download:
    if os.path.exists(model_path):
        files.download(model_path)
        print(f"Скачан: {model_path}")